
name: CD

on:  
  push:
    branches: [ main ]
  
  workflow_dispatch:

jobs:
        
  CD:
 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1.1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with: 
          
          namespace: |
            vote  
          manifests: |
            ./deployments/deploy-db.yaml
            ./deployments/deploy-redis.yaml
            ./deployments/deploy-result.yaml
            ./deployments/deploy-vote.yaml
            ./deployments/deploy-worker2.yaml
            ./services/db.yaml
            ./services/redis.yaml
            ./services/result.yaml
            ./services/vote.yaml
            ./ingress/ingress-voto.yaml
            ./ingress/ingress-resultado.yaml
      
